name: check-seeds

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/check-seeds.yml
      - api/db/seeds/**
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  seed-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code, setup node and install dependencies
        uses: edp5/edp5-actions/checkout-node@v1.9.0
        with:
          file-version: .nvmrc
          installCommand: |
            npm ci
            cp sample.env .env
          workingDirectory: ./api

      - name: Setup docker compose
        uses: edp5/edp5-actions/setup-docker-compose@v1.9.0
        with:
          waitTime: '2'
          path: ./api

      - name: Create database
        run: npm run db:create
        working-directory: ./api

      - name: run migrations
        run: npm run db:migrate
        working-directory: ./api

      - name: Run seeds
        run: npm run db:seed
        working-directory: ./api
