name: check-migrations

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/check-migrations.yml
      - api/db/migrations/**
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  migration-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: configure project
        run: |
          npm ci
          cp sample.env .env
        working-directory: ./api

      - name: Setup docker compose
        uses: edp5/edp5-actions/setup-docker-compose@v1.6.0
        with:
          waitTime: '2'

      - name: Create database
        run: npm run db:create
        working-directory: ./api

      - name: run migrations
        run: npm run db:migrate
        working-directory: ./api

      - name: Get file number in migration directory
        id: get_migration_files
        run: echo "migration_files=$(ls *.js | wc -l)" >> $GITHUB_OUTPUT
        working-directory: ./api/db/migrations

      - name: Rollback all migrations
        run: |
          for i in $(seq 1 ${{ steps.get_migration_files.outputs.migration_files }}); do
            npm run db:rollback:latest
            done
        working-directory: ./api
