name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: call release
        uses: edp5/edp5-actions/release@main
        with:
          token: ${{ secrets.SERVICE_TOKEN }}
